import os

APP_HOST = os.getenv("APP_HOST", "localhost")

RABBITMQ_HOST = os.getenv("RABBITMQ_HOST", "192.168.1.102")
RABBITMQ_PORT = os.getenv("RABBITMQ_PORT", "5672")
RABBITMQ_USER = os.getenv("RABBITMQ_USER", "guest")
RABBITMQ_PASSWORD = os.getenv("RABBITMQ_PASSWORD", "guest")

TRANSACTION_SERVICE_HOST = os.getenv("TRANSACTION_SERVICE_HOST", "192.168.1.102")
TRANSACTION_SERVICE_PORT = os.getenv("TRANSACTION_SERVICE_PORT", "8080")
